import sys

hintList = '''
Example
<5N CM ET PA XX CF EQ PA XF CK EW PG XE CR E7 PU YU>
<AN YV NB OA 7Q YL NB OQ GQ 50 RF M6 76 Y7 NB OZ G6 Y6 N1 O8 7Q 5Q RA MU GW HW>
How do I cross the red Line?
<5N CS EQ P0 XY TY I1 AU HD CD M9 G8 5E TE>
<5N C8 E7 PV XB TB IR AE H6 CU EE PA HA TT IM AF XF CV EU PE XU CT EX PO XT TT IL AD H1 TJ IT AS HH TM IS PK YK>
<AN Y5 NI OO GO 59 RV MU G5 Y5 NN OA 7H YJ NT MT GJ 5D RU OU 7A YD N0 OP 7Z Y9 N1 O8 7F 5R TR>
Why is the guru laughing?
<AN Y5 N6 O0 G0 5B RJ MU 70 50 RF MJ GT YT N5 OS PS>
<MN PD X0 CH EV AV HH TA IF PF XV CU EK A9 HR CR ET PZ XB C5 I5 AU H1 T9 IR PR XL CH ES PF XM C5 EN PG XP TP I8 AQ HA RA>
<5N CV E7 PL HL TT IJ AF HE TF IZ AD HF CF EL PQ XK TK I1  AI HN TH EH PZ XK CZ EF P0 XZ TZ IF AM 5M>
How do I drop the wristband?
<TM OO 7P YJ N9 MD 7D Y0 NP OS GM 5F NF OZ 7P 5U TU>
<5A C7 EE PP XS TR ER G5 Y7 NA MA GS 5O R0 MZ GB 5X RB MV GW YW ND OX 7Q YA RA MP GX 56 N6 OW 7K YY NH MH G0 5B RJ MO 7O YS NP OI GI 5J R0 MP 7S 5P NS ES>
<TA OQ 7S Y1 R1 M9 GI 5S RH MM GS YS NF OJ 7U YD NL OB 7V 5V RN MI 7I YO NS MS GH 50 N0 OL 7D YA RA MK GV 55 T5>
How do I get into the shed?
<TN OV 79 YU N7 M7 GY 5E RA OX 7Q 5Q RS M5 GN 5T RN M0 70 YQ NV OA 7O YS NB OA PA>
<MN PF XL CW ER PH HH TY I7 P7 XL CD EX AX HO TS IQ AK HW TQ IW AM XM CI EP PO X1 CJ IJ A5 HG TK IY PY XA CE EZ 7Z>
<MN PV X7 CL IL A7 HY T9 IG PG XZ CB E6 P0 X9 CR I7 P7 5V RB MD G9 5D RY OR PR>
What does the guru want?
<5N CG E5 AH XH CS ED AF HS CS EP PX XB TB ID PD 5K RZ MK GQ 5F NF I0 AJ HQ RQ>
<5N CV E9 P0 H0 TJ IQ AX H6 TF IX PX XT CL IL AW HQ T8 IZ AK HU T5 IN A6 HO CE IE AP H8 C8 EF P6 X8 C5 I5 7N YS N6 OF 70 YH NJ OP 7I Y1 C1>
<5N CG E5 PU HU T5 IY AT XT CG EK P0 XK CF EG AG H1 T6 IN AV 5V>
How do I get past the guards?
<MN PE XG CJ E1 A1 HY T5 IS AY XY CW EU PJ X1 CY E5 PR X7 C5 O5>
<TN OD 7U YE NI OG 7Z YH RH MS GA YA NQ OZ 7K YA RA MY GE 5A RU OU 7A YP NO OL GL 57 RY M9 79 YO NP OS 7D YU NB ML 7B 5L TL>
<5N CF EL PZ XP TP II AM HD TU EU PA XH CJ EV PD HD TY I7 A8 X8 CF EJ AJ HI T7 I6 AW XW CK IK AL HW TF IQ AJ H9 C9 EW PU XE TE IU AV HW TY I7 AO XV NV>
What do I do with the note?
<TN OV 77 YL RL MH GR 5Y RH MS GP 5H NH OS 7D 5I TI>
<5N CI E5 A5 H6 TF IV AK HU TB EB PX XH CA EF PD XJ CT EL A8 X8 CF EJ PQ HB TX EX PB XM CW IW AR HH TT IR A5 HI TR ER P5 XU TV MV>
<TN OA 7E Y8 NE OA 7D 5D RV MK 7K YW NY MY PA XD CL EB PZ XH TH IT AL HV TB IU GU>
How do I buy things?
<5N C0 EQ PM HS TR IS PS XP CI EP PG HG T1 I6 AL HW TG I7 AI H5 T7 E7 PY XI TI I0 AJ HV T5 IS GS>
<MN PD XU CW EP P7 XM TM IB AZ HO TX I5 P5 XY CT EZ PK HK TW IR AH XH C1 EI PP XZ CP E8 A8 HD TB IM A7 HP TI I9 AI XI CJ EB PX XH TH IN AI H5 TS I1 G1>
<MN P8 XQ CF EX P7 XG TG IW A6 HF CF E8 PS XX CF E5 PS XF TD ED PQ XM CB EL PQ XA CF EX PN HN TM IA AD HU T8 I7 AP H7 TL ML>
How do I get the lead?
<TA OO 7L 5J RO OO 7G YM N5 OS 7N YS N5 OX GX 5T RA OA 7Q YZ NK MK GY 57 RX MG AG>
<MA PF XS C5 I5 AN HG TF EF PS XT CH EL PI HI TK IV AK HF RF>
How do I read the tomes?
<MA P5 XN C8 EE AE H7 C7 EU PX XN CT EN AN XH TH O5 7R YM N7 M7 GI 5K NK OR 7Y YD NM EM>
<TA OQ 7Z YF NS MS GM 5A RI MP 7P YM ND MD GB YB N5 ON 76 Y1 N0 ON GT YT NH OO 7L YW NR MR GY 5X RY OE GE X8 C5 EJ AJ XL R9 M1 GG 5W NW IY A0 H9 TD I9 PK YK>
<AA YQ NZ OK 7Y YT RT MX GQ YQ NJ OF GF 5M RO MA GD 5V NV OF 7K YG NO MO 77 57 RS M5 GU YU NT OM 7Q 5B RM M7 77 YU NW OR 7W YM RM MW GU 5N NN OV 7H Y1 NJ O9 G9 5U R5 O5 7R Y7 R7 MR GE 5D NZ EZ>
How do I use the aerosoul?
<TX OO 7S 5R NR O5 7U 56 R5 O5 7I YN NV MV GU YU N7 OQ 78 YL N8 OW 7V Y8 R8 MZ GF 5S RD MB GW 5L N8 M8 GN 5H RT MZ GP YE N7 OV 7E YA RM IM>
<TX O9 78 Y7 R7 MR GH 5R RT OT 7J YF RF M9 GU 5O RU OU 77 YY NS O5 7G YN NX MX GM 5P RJ MO GL HL>
<AX XO TX EO GP 5S RN ON 7V Y9 N0 ON GN 5H RJ MO GL YL N1 OJ GJ 5Z RT MY GW 56 RZ ME 7E YM N7 OE 7M 5M NM EM>
<TX IU AE HA TB IA PA XT CM E0 PM XI CP IS GS>
How do I kill Kronos?
<TN OF 7L YD N9 O0 G0 5U R9 MI GK YK NV O6 G6 57 RM ME GG 55 RV ME 7E YS NR O1 7J YO RO MR GE 5P RM MH GP YP NL OI PI>
<MM PW XU CN IE AO HE CE EY PT XY CH IH AX HN TT I9 P9 XW CR EE PP HP TO IX AP HZ TQ I8 A5 X5 C6 E1 PR XW C0 E9 79>
<MA PK XV C5 I5 AT H0 TP IZ PZ XU C9 ED P9 H9 TV I1 AD XD C0 EF AF HL TQ IX PX XY CR E5 P8 Y8>
<AS YD NJ OP 7X Y6 R6 M7 GG 5O NO OK 7V YN NY O7 7R 5R RP MX GB 5X RY MT 7T YH N0 M0 GB 5J RU IU>
<TS O1 76 YE RE MM GT 5A NX OB GB 5Q R8 ME 7E YO NS OP 7H 5H R0 MQ 7Q Y6 N1 M1 GV 5N TN>
<5N C0 EQ PM HM TN II AW HQ T6 E6 P7 XV CH IH A0 HB TV EV PN XR CH EL P6 X1 C8 E7 PX XY CT EH PL HL TK IZ AR H5 TA IE PE YE>
Where's the thermonuciear device?
<MS PD XA CK IK AW XW C0 EQ PK XO CE EA PQ X8 CL E7 A7 HA TO IH AO HG T9 I0 AF HM CM EA P7 XD CU EK PI XW CR EH AM XM TS OR 7E YU NB MB GZ 5J NJ OT 7S Y5 R5 O5 A8 HQ TF ID AB HL TT EO AE XE CF E6 PN XR CY E0 PP HS CP IS GS>
How do I use the platform?
<MX PU XE CA EQ P8 X1 C0 I0 AN HI TW E1 PI XP TP O5 78 Y9 N6 O1 7G XG>
<AX YB N0 O9 G9 5T RN M5 GU 58 R9 MG GM YM NO OP 70 50 RQ MJ GV 5H NH OA 7T YY RY MZ GL 57 N7 OY 7I 5I RK MZ G6 5Z RF M0 GZ YZ NF OB GB 5R RE M6 7U YE NA MA PY XK CV EW PU X7 N7>
<5X CB E0 PD XZ CU IU AW H9 C9 EU P5 H5 TN I8 P8 X6 T6 IZ AL HH TP II PI XJ C1 EV P8 XK C6 E9 PK HK TQ IF AV H9 TU IK AZ 5Z>
What can I do with the devil?
<MA PQ XS C1 I1 A0 HQ TL IB AQ XQ C5 EY PR X9 T9 IV AB XB CD EM PR XK NK>
How do I get past the cream doors?
<5A CY EE PR XO CN IN PR 5Y RK MZ 7Z YE NR O1 G1 5G RK MY GT YT NU OW 7I 5R RW ML 7L YQ NJ OT 7M 5M RA M7 GD 5U RK MI GW 5R RH MZ 75 5R TR>
<5X C7 EG PO XR CM IM AW HU TN EN PR XY CL EW PV H8 TE EE PN XI CK IK AI HE TA EA PU XE CG E1 PY XO CP ES PN YN>
How do I work the lift?
<5M CD EX PR XX CP ES AS HH T0 M0>
<TM OV 7U Y9 NR MR GG 55 R8 O8 7W YG RN OG GN HN>
<AM YP NZ M0 GP YP NN OU 77 Y6 R6 MZ GF 59 R0 O0 7J 5J RP MI GG 5A NA OG 7E Y5 NU EU>
<TM OA 7T YR RR M5 GU YU N1 O9 7I 5I R9 MD G0 51 RV MW G1 Y1 N0 OQ 70 YO NJ EJ>
How do I vote?
<TM OW 7U YN RN MG GO 5G RP OP 7O 5O RY MR GS 5R RE M8 78 YM NA O6 7F YX RX OR GR XY CK EZ AZ HE TR I1 P1 X9 C6 I6 A8 H1 T9 IG AH HX TT IL AO XO CS EQ AQ HX TP IE AA HQ TZ IF A0 HZ C5 O5>
<TM OF 7X Y9 R9 MD GL 5D RK M6 G9 5K NK OG 7N YS N5 O8 G8 5E RI MP 7P YJ NH OP PP>
<MA PQ XZ CK IK AR HY TI IP PP XM CD ID AZ HB TX EX PS XF TF I6 AL HI TK IA PA XM CD ID A0 HH CH EO PA XD CM EF AF HQ T7 IQ A8 H6 TN I8 G8>
<MA PN XX CT EA PX HX TT IR AH HA TG I5 A7 HI TT IH A5 HH TV EV P5 XI C9 E8 P7 XR CT IT AK H6 TZ I6 P6 XB CZ EH P0 H0 TN II AW XW CP EX PT XA CQ EX 7X>
How do I kill the adventurer?
<TM OP GH 5N NN OG 75 YU RU M7 G8 55 RS OS AH XH CG EI P5 H5 TA IH AM HE TR I7 AM XM CF EL PQ XX TX IG AE HY TH EH PA XS TS ID AJ HB TL IJ PQ HJ RJ>
<5M CV EB P1 XB T1 E1 PV X6 T6 IO AS HB CB E9 PY XW CG IN PG HN TI I5 AH HV CV ML GH 5A RT MM GD YD N8 O6 79 59 RV MB G1 5H TH>
How do I get past the dragon?
<AA YQ NZ OK GK 5L RH MT GO 5S RP OP 7M YD RD M7 GM 5B RR OR 7K Y8 N9 OG 7W 5F RS MH GP 5A RQ M8 GF HF>
<AA YP NI MI G7 5U NU OV 7J YO NS MS G6 5F RX M9 79 YV N5 OI 7R YW NM EM>
<TA OQ 7S Y1 R1 MG G7 5Y RZ MF G0 5Z NZ OQ 7L Y6 R6 M5 GG 5M R7 M6 GW 58 R1 MW 7W YL N8 ON 7X 5X RB MZ 7Z YK NW OG PG>
<MA PP XI TI I5 AS H5 TX IQ PQ XA CH IH AX HS T6 IF PF XM CO EG PM HM TP I7 AP HL T6 IK AU HV TN IX A5 X5 CN E8 A8 HS T5 IH A5 55>
How do I move the wheelbarrow?
<AN YV N9 O0 G0 5G R7 MM G7 5P RR MY GK 5Y R7 MB 7B YJ NO MO G1 5J RP M8 78 YK NZ OL 7Y YD CD>
<5X CB E0 P9 H9 TO IM A7 HM TI IH AT HZ TT IM AV XV C1 EG AG HN TI IK PK KL CW EY PN XE CY ET PR HR T9 I8 P8 XB CV IV A0 HQ TN IX A5 X5 TT ET PG XO CL IL A7 HY T9 EK PY XT TT IL AD HA TD IY PY XD CL EP AP HO TJ I8 AQ H6 C6 E9 P8 XS TP ES 7S>
How do I get through the double doors?
<MA PN XX TX IU AW HQ TL IO AG 5G>
<AA YI NG ON 70 50 RH MS GY 5T RL IL>
<TA OM 7H YY RY M1 GV 5S NS OD 7J Y1 R1 MH GA 5D RS M5 G8 H8>
<AA YH N0 OB 7V Y7 NB OJ 7O YG RG MF GJ 5H NP O7 7P 5P R0 MW GU 55 RA MP 7P Y8 N9 OY 7K 5K RJ MD GB 5L R9 M0 GP HP>
How do I get past the paper wall room?
<AM Y8 N6 OA 7E YU RU MQ GF 50 N0 OK 7Z 5Z RP MX GF 50 T0>
<5M CW EU PN HN TT IM AT HE CE EG PN HN TV I9 A0 X0 CW EI PL X1 C6 E8 P5 XX NX>
<5M CW EU PN HN TG IO AG HP CP EO H0 TQ I7 AM 5M>
I’ve won but not with full score. Why?
<TN OY GG 5M NM MB 7S 5R NR OP 7L YO RO EA AA HP TO I1 AJ HQ CB EX AX HA TH I0 P0 XJ TJ IR AW HU TX IN A6 X6 CJ EF PU H0 C0 EG P7 XL TN EN GY YY NH OA 7T 5O RL OL 7V YW NU OA GG YG NW O6 7F YS N5 M5 GU 51 RV MW G1 5G NG OS 7B YA NQ MQ GZ 5L RI ML GW 5V NJ MJ GT 5S RX MB 7Q YX RX MS GR 5S NP MS 7P XP>
<AX Y5 NR OT GT 5U RW MI 7I YT NS O5 7N YV RO IO>
<TX O9 78 Y7 R7 MR GH 5R RT OT 7J YF RF MU GN 50 N0 O1 7I Y7 NR OM 7D 5D RQ M0 GO YO R0 O0 7Y YT NM O8 7L YW CW>
<5X C6 EW PL XO CM E7 PV HV TH IA AF XF C6 E9 PQ X0 CN EX P5 H5 TY IN A8 X8 CZ EO PJ XB C6 I6 A1 HI CI E5 PG XW TW EF AF HU TN I0 P0 XB CJ EU AU HW TV IB GB>
<MX PH XT CW EL AL H7 TY I9 P9 XW CU EN PG XP TP IZ AQ H8 C8 MM GT 5J NJ IR AS HX TO IL PN YN>
<AX YB NM OW GW 5P RX MB GX 5T RA MX 7X YT NJ MJ GR 5W RU MX GN 56 RZ ME AE>
<MX PD XM C7 I7 A6 HW TL EL PH XS CM EO PL HL TT IM AB HX CX EP PT HT TX IR AJ HV TB I9 A0 HF TM MM>
<TM OT 7S 5S R8 MQ GW 5Q NW MW GH 5X RP OP 71 Y9 N6 O7 7U 5U RX MN G6 5V RB M6 G7 5I RN MG 7N 5G NN MN GH 5T RE MA 7A Y7 NY MY GZ 5F RM MO 7O YL NF O6 G6 55 RA MH GL 5W NW OM 7T Y0 RZ MR GH YH NP OX 7B 5D TD>
What about the alchemists?
<MM PP HP TG I5 AI XR C9 I9 AF H0 TQ I5 PH HH TW I6 A8 HE CE E7 PS XO CZ EP AP HZ TQ I8 AZ X5 N5>
<5M CF EL PW X8 C5 I5 AR HT TY IR PR XE C5 I5 AE HR TE IM PM XP C0 EF AD HS CS EU PN XY C1 EJ AJ HD TB IS AD HU CU EQ PM XP C0 ED PZ XK NK>
<5M CF EL PW HW T1 IR AW HI CI EE P7 XA TA IB AZ H8 TQ EQ PD XL CD EV AJ XJ CP EI PA XE CP ER PH XL TB EL AB XG NG>
<5A CK EV P5 H7 TP I7 P7 XR CH EK PZ XT TT IO AG HW CW EG P7 XM TM IS AO HE TM EH AH Y5 NS OX 75 55 RR M7 G6 51 N1 OW 7U Y0 N1 M1 GZ 5L RB OQ 7A 5A RN MX 7X Y5 NG ON 7X 5S NS ES>
Where do I find some light?
<5M CW EU PN HN TG IO AG HP CP EZ PB HB TQ IL AY HT CT EJ  PD XU TU I6 AE HU TN EN PF XL CZ EP AP HA TE EE PD XB CL  EO PJ HQ CQ MA GP 5I R5 O5 7H YS NF OM 77 YR RR M9 G8 Y8 NK O6 7L XL>
<AM YH NA OU GU 57 RM MA GD 58 RK OK 7I YE NA MA G5 5H RR MY GK 56 R9 MK AK>
<MA PE XO CG EM P7 XR C9 E1 PI XQ TQ O7 7G YF NS OH 7G Y1 YS>
<AA YI N7 OZ GZ 5P RA ME GP HP>
How do I get into the tree?
<5N CU EK PF XJ CK ED AD HS TT IY PY XH CA EH PL HL C6 I6 7L YP N0 OH GH XS TS ID AU H0 TU EU PT XM CQ IQ A8 HX TN I6 AO HL TF IZ AD HF CR OR>
<TN OV 77 YL RL MO GM 57 N7 OB 7Z YB NU OD 7Z 5Z RB ML GW HW>
<AN YV N9 O0 G0 5W RK MI 7I Y9 N1 OY GY 57 RR OR 79 YV NB MB G9 51 RY IY>
Floorboards - How do I move them?
<5N CV E9 P0 XN TN IH AA HV TB EB PE XA CD EY AY HT TH IZ AF HK TA MA>
<TN OF 76 YN NX MX G9 58 R7 O7 7S YO N0 OF GF 5Z RD OD 7B 5B R8 M6 GN 5G NB EB>
<TN OV 79 Y0 NF MF GS 5T R0 MH 7H Y0 NB OV GV 5D RL MD GA YG RG E5 GP YU CU>
How do I get past the boulders?
<TN O7 7I Y5 NX MX GS YS NR OH 7K YZ NT M8 A8>
<MN 7G 5N NG I5 A8 X8 CE ED PL YL>
<AM YH NA OU GU 58 RW MA 7A YQ NZ OK 7Q 5Q RA MH GP 5I RK M8 GQ 5S TS>
'''

requiredPoints = { 'A': 0, 'B': 1, 'C': 10, 'D': 20, 'E': 30 }
decodeString = 'COPYRIGHTMA5NE7XSKW0JLZ1986BDFQUV234!'

# Hints are encoded with a random (0..3) offset. Two hints are not following this pattern.
# That might be a bug in the original hint.
def encodeHint(inStr,offset=0):
	outputStr = ''
	xorVal = 10
	for ch in inStr + chr(0):
		byteVal = ord(ch)
		byteValXor = byteVal
		byteVal ^= xorVal
		xorVal ^= byteValXor
		outputStr += decodeString[((byteVal >> 3) & 0x1C) + offset]
		offset += 1
		if offset > 3:
			offset = 0
		outputStr += decodeString[(byteVal & 0x1F) + 1]
		outputStr += ' '
	return '<' + outputStr.strip() + '>'

def decodeHint(inStr):
	firstChar = True
	xorVal = 10
	outputStr = ''
	for ch in inStr:
		if ch == ' ':
			continue
		idx = decodeString.find(ch.upper())
		if idx < 0:
			return
		if firstChar:
			firstChar = False
			byteVal = (idx & 0x1C) << 3
		else:
			firstChar = True
			byteVal |= (idx - 1) & 0x1F
			byteVal ^= xorVal
			xorVal ^= byteVal
			if byteVal:
				outputStr += chr(byteVal)
	return outputStr

for line in hintList.split('\n'):
	if len(line) == 0:
		continue
	if line[0]!='<':
		print()
		print("Question: %s" % line)
	else:
		hint = line[1:-1]
		output = decodeHint(hint)
		print("Hint (required Points: %d) '%s'" % (requiredPoints[output[0]], output[1:]))
